// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Male                 bool     `protobuf:"varint,2,opt,name=male,proto3" json:"male,omitempty"`
	Scores               []int32  `protobuf:"varint,3,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetMale() bool {
	if m != nil {
		return m.Male
	}
	return false
}

func (m *Student) GetScores() []int32 {
	if m != nil {
		return m.Scores
	}
	return nil
}

type SearchRequest struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{1}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type SearchResponse struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	Res                  string   `protobuf:"bytes,22,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{2}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *SearchResponse) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

func init() {
	proto.RegisterType((*Student)(nil), "proto.Student")
	proto.RegisterType((*SearchRequest)(nil), "proto.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "proto.SearchResponse")
}

func init() { proto.RegisterFile("student.proto", fileDescriptor_94a1c1b032ad0c00) }

var fileDescriptor_94a1c1b032ad0c00 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xd1, 0xca, 0x82, 0x40,
	0x10, 0x85, 0xd9, 0xdf, 0x5f, 0xab, 0x21, 0x23, 0x86, 0x12, 0x09, 0x02, 0xf1, 0xca, 0x2b, 0x89,
	0xa2, 0x57, 0x08, 0xba, 0x5d, 0x9f, 0xc0, 0x6c, 0xa0, 0x20, 0x5d, 0xdb, 0x59, 0x7b, 0xfe, 0x70,
	0x57, 0x2f, 0xec, 0x6a, 0xce, 0xf9, 0x0e, 0x9c, 0xc3, 0x40, 0xc8, 0xa6, 0xbb, 0x53, 0x63, 0xf2,
	0x56, 0x2b, 0xa3, 0xd0, 0xb7, 0x27, 0xbd, 0xc2, 0xac, 0x70, 0x1c, 0x11, 0xfe, 0x9b, 0xb2, 0xa6,
	0x58, 0x24, 0x22, 0x5b, 0x48, 0xab, 0x7b, 0x56, 0x97, 0x2f, 0x8a, 0xff, 0x12, 0x91, 0xcd, 0xa5,
	0xd5, 0x18, 0x41, 0xc0, 0x95, 0xd2, 0xc4, 0xb1, 0x97, 0x78, 0x99, 0x2f, 0x07, 0x97, 0xee, 0x21,
	0x2c, 0xa8, 0xd4, 0xd5, 0x43, 0xd2, 0xbb, 0x23, 0x36, 0xb8, 0x04, 0xc1, 0x43, 0x9b, 0xe0, 0xf4,
	0x00, 0xab, 0x31, 0xe6, 0x56, 0x35, 0x4c, 0xd3, 0x1c, 0xd7, 0xe0, 0xf5, 0x9d, 0x91, 0xf5, 0xbd,
	0x3c, 0x5e, 0xc6, 0xc2, 0x82, 0xf4, 0xe7, 0x59, 0x11, 0x9e, 0x21, 0x70, 0x00, 0x37, 0xee, 0x8b,
	0x7c, 0x32, 0xb8, 0xdb, 0xfe, 0x50, 0xb7, 0x73, 0x0b, 0x2c, 0x3d, 0x7d, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xbc, 0xbe, 0x03, 0x77, 0x02, 0x01, 0x00, 0x00,
}
